{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'
         html_class='full'}
{if eq( $attribute.contentclassattribute_id, '329')}
{def $current=$attribute.data_text|wash( xhtml )
     $productions=array( array('01','Alaska'), array('02','Chicago'), array('03','New York'), array('05','Georgia'), array('05','Washington'))}
<select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_ezselect_selected_array_{$attribute.id}[]" {* section show=$attribute.class_content.is_multiselect}multiple{/section *}>
<option value=""{if eq( $current, '')} selected {/if}>&nbsp;</option>
{foreach $productions as $production}
  <option value="{$production.0}"{if eq( $current, $production.1)} selected {/if}>{$production.1}</option>
{/foreach}
</select>
{else}
<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ezstring_data_text_{$attribute.id}" value="{$attribute.data_text|wash( xhtml )}" />
{/if}
{/default}
